server:
  port: 8082

spring:
# 数据库
  datasource:
     url: jdbc:mysql://39.104.160.80:3306/guoyan?characterEncoding=UTF-8
     username: gydb
     password: gy123456
     driver-class-name: com.mysql.jdbc.Driver

# 配置redis
  redis:
#     host: 101.200.166.221
     host: 47.94.108.128
     password: sang123456
#      host: 127.0.0.1
     port: 6379

mybatis:
    # mybatis.config= classpath:mybatis-config.xml
    mapperLocations: classpath:mappers/*.xml
    # domain object's package
    typeAliasesPackage: cn.xdc.bean


